### PR TITLE
initial fastlane structures

### PR DESCRIPTION
**Pull request by IzzySoft**
In preparation of your potential listing with F-Droid.org – but also for your (now) existing listing in my repo: using these (standard) structures, you can maintain your app's metadata yourself in one place, and feed them all (also works for Play Store). Please expand by e.g. moving your screenshots in. My [Fastlane Cheat Sheet](https://gitlab.com/snippets/1895688) might be helpful as guide.

The format I've used for `full_description.txt` is what I call "Markdown lite" and proved the best compromise for all 3 places (i.e. it works fine with all 3 of them). Find a few hints on that [in my wiki](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane).

### CODE REVIEW

**Comment by IzzySoft** [comment]
Thanks! If you want to add a new badge to your Readme, [here is mine](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) – and [this would be the link target](https://apt.izzysoft.de/fdroid/index/apk/com.ethereal.openscan) :smiley:

**Comment by IzzySoft** [comment]
PS: Should you add screenshots and/or per-release changelogs, please let me know so I can enable them on my end.

**Comment by veejayts** [comment]
Thank you so much for the PR! I pushed the phone screenshots to fastlane according to the specs. It would be much appreciated if the screenshots were enabled and synched to your repo.

I do have a question. Will the screenshots be updated for each release or will it update itself each time the fastlane directory in this repo is changed?

**Comment by IzzySoft** [comment]
> It would be much appreciated if the screenshots were enabled and synched to your repo.

Just synced them manually and enabled them for future updates.

> Will the screenshots be updated for each release or will it update itself each time the fastlane directory in this repo is changed?

Whenever a new release is fetched, fastlane is checked on files "newer than" what's already here. For screenshots, that also includes purging here what's no longer there – but only if new screenshot(s) were found.

Thanks for adding the download button! :green_heart:

**Comment by veejayts** [comment]
Thank YOU ❤️

**Pull request merged**
